project:
  type: "website"

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/patel-zeel
      - icon: twitter
        href: https://twitter.com/patel_zeel_
format:
  html:
    theme: cosmo
    css: styles.css